### ISSUE TITLE
Cert-manager error

### ISSUE THREAD

**Issue by MatiasLGonzalez** [sakkiii/apache-nifi-helm#1]
I'm getting the following error when trying to use your helm chart:
`Failed to run helm install on specified args: Error: INSTALLATION FAILED: 1 error occurred: * admission webhook "webhook.cert-manager.io" denied the request: spec.keystores.pkcs12: Forbidden: must set exactly one of passwordSecretRef and password must for PKCS#12 keystores : exit status 1`

I'm using k3s v1.32.3+k3s1 with helm 3.17.2, I used the following values.yaml:

```yaml
image:
  repository: apache/nifi
  tag: 1.16.0

replicaCount: 3

service:
  type: LoadBalancer

persistence:
  enabled: true
  storageClass: efs

monitoring:
  prometheus: true
```

Otherwise awesome project

**Comment by sakkiii** [comment]
Hey @MatiasLGonzalez 

Please create secret and add in the values file

```
  tls:
    certificate:
      duration: 8760h # 365 days
      renewBefore: 168h # 7 days
      keystorePasswordSecretRef:
        name: ""
        key: password

  encryption:
    sensitivePropertiesKey:
      secretRef:
        name: ""
        key: "" 
```
